#!/usr/bin/env bash
# route-selected.sh — Routes selected newsletter articles to corresponding GitHub repos
# Usage: ./route-selected.sh <digest-selections.json>
#
# Input JSON format (generated by digest HTML export):
# {
#   "date": "2026-03-11",
#   "pharma": [ { "title": "...", "source": "...", "summary": "..." } ],
#   "hbr":    [ { "title": "...", "source": "...", "summary": "..." } ],
#   "ai":     [ { "title": "...", "source": "...", "summary": "..." } ]
# }

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SELECTIONS_FILE="${1:?Usage: $0 <digest-selections.json>}"

# --- Configuration ---
# Adjust these paths to match your local repo locations
PHARMA_REPO="${PHARMA_REPO:-$HOME/github/pharma-decipher}"
HBR_REPO="${HBR_REPO:-$HOME/github/hbr-review}"
AI_REPO="${AI_REPO:-$HOME/github/ai-articles}"

DATE=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['date'])" "$SELECTIONS_FILE")

route_to_repo() {
    local repo_path="$1"
    local category="$2"
    local repo_name
    repo_name=$(basename "$repo_path")

    # Extract articles for this category into markdown
    local md_content
    md_content=$(python3 -c "
import json, sys

data = json.load(open(sys.argv[1]))
articles = data.get(sys.argv[2], [])
if not articles:
    sys.exit(0)

date = data['date']
print(f'# {sys.argv[2].upper()} Articles — {date}')
print()
for i, a in enumerate(articles, 1):
    print(f'## {i}. {a[\"title\"]}')
    print(f'**Source:** {a.get(\"source\", \"N/A\")}')
    print()
    print(a.get('summary', ''))
    print()
    if 'url' in a:
        print(f'[Original]({a[\"url\"]})')
        print()
" "$SELECTIONS_FILE" "$category")

    if [ -z "$md_content" ]; then
        echo "[$repo_name] No articles for category: $category — skipping"
        return
    fi

    # Ensure inbox directory exists
    mkdir -p "$repo_path/inbox"

    # Write markdown file
    local target_file="$repo_path/inbox/${DATE}.md"
    echo "$md_content" > "$target_file"
    echo "[$repo_name] Wrote $(echo "$md_content" | wc -l) lines → $target_file"

    # Git add, commit, push
    (
        cd "$repo_path"
        git add "inbox/${DATE}.md"
        git commit -m "Add newsletter articles for ${DATE}

Routed from daily digest pipeline."
        git push origin HEAD
    )
    echo "[$repo_name] Pushed to remote"
}

echo "=== Newsletter Route — $DATE ==="
echo ""

route_to_repo "$PHARMA_REPO" "pharma"
route_to_repo "$HBR_REPO" "hbr"
route_to_repo "$AI_REPO" "ai"

echo ""
echo "=== Done. All selected articles routed. ==="
